### PR TITLE
Rename function parameters using a reserved keyword

### PR DESCRIPTION
**Pull request by HGuillemet**
Appends a `_` to the name of function parameters when they clash with a Java reserved keyword.

### CODE REVIEW

**Comment by saudet** [comment]
Please add those in here:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/InfoMap.java#L171

**Comment by HGuillemet** [comment]
Ok, I hadn't realized that the infoMap was queried for function parameter names.

**Comment by saudet** [comment]
It should, for that particular case, it's not?

**Comment by HGuillemet** [comment]
Yes it is. New commit adds `_` to parameter names like `interface`.

**Comment by HGuillemet** [comment]
Added another small fix to prevent generation of successive `...` in containers

**Comment by saudet** [comment]
What happens if we don't use filterJavaAnnotations()? Let's name it maybe constructorAnnotations()?

**Comment by HGuillemet** [comment]
Without the commit, if we have an info like `new Info("deprecated").annotations("@Deprecated"))` and a C++ constructor is deprecated, the `@Deprecated` annotation goes on `allocate` and not on the public Java constructor.
The idea of `filterJavaAnnotations`  is to retain from a string of annotations only those that are meaningful for non-native Java methods, thus the name.
I only though of `@Deprecated` but there may be others. Ideally this would be all non-JavaCPP annotations.

`

**Comment by saudet** [comment]
Right, but can we just leave all annotations without any issues? Does it break something?

**Comment by HGuillemet** [comment]
Ah. You mean place all annotations on both annotate and the constructor ?
There are already the JavaCPP parameter annotations that are places uselessly on constructor parameters, so why not also place the method annotations, if you prefer...

**Comment by saudet** [comment]
Right, it's not exactly useless, so let's so that for the method annotations too if it works

**Comment by HGuillemet** [comment]
> Does it break something?

In fact it does, because some annotations that are valid on `allocate` (an `ElementType.METHOD`) are not on constructors (an `ElementType.CONSTRUCTOR`), like `@Adapter`.
So I guess we must filter the annotations to place on constructor according to some white list (I suggested: `@Deprecated` only).

**Comment by saudet** [comment]
Sounds good

**Comment by HGuillemet** [comment]
Ok, Can you merge if you agree with these changes ? I'd like to push an update or Pytorch presets that uses them.

**Review by saudet — APPROVED** [review]

**Review by saudet — APPROVED** [review]

**Pull request merged**
