### PR TITLE
Enable JavaCPP in OSGi

### PR DESCRIPTION
**Pull request by timothyjward**
Following on from discussions in PR #328 this PR takes the separated Maven Plugin layout and

1. Adds OSGi metadata to the JavaCPP library
2. Adds an OSGi integration test

Note that the integration test passes because the JavaCPP `Loader.load()` method is not used, if it is used then the test fails. This demonstrates how the native library loading done by JavaCPP fails in OSGi, and hopefully can be used to design a fix.

### CODE REVIEW

**Comment by saudet** [comment]
Crap, this is annoying. I thought "Rebase and merge" wouldn't cause conflicts like that. Could you rebase this PR? I'd merge this in the "osgi" branch. I'll look at the other PR and see if it makes sense to merge that one to the master branch.

**Comment by timothyjward** [comment]
> Crap, this is annoying. I thought "Rebase and merge" wouldn't cause conflicts like that. Could you rebase this PR? I'd merge this in the "osgi" branch. I'll look at the other PR and see if it makes sense to merge that one to the master branch.

Git is pretty amazing, which is part of what makes it so surprising when it doesn't work. I'll get this properly rebased on top of the bytedeco/osgi branch and force push.

**Comment by timothyjward** [comment]
For some reason the maven-plugin commit had changed id, which was the cause of our woes. I just cherry-picked the other changes on top of the osgi branch so we should be good to go now.

**Comment by saudet** [comment]
BTW, the test fails so snapshots are not getting deployed:
https://travis-ci.org/bytedeco/javacpp/builds/574871037

**Pull request merged**
