### PR TITLE
squid:CommentedOutCodeLine - Sections of code should not be "commented out"

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rule squid:CommentedOutCodeLine - Sections of code should not be "commented out".
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3ACommentedOutCodeLine
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by saudet** [comment]
Looking good, thanks! Just two things before I merge this:
1. Let's also remove the obsolete comments from the default constructor of `Pointer`.
2. In `Generator`, there is a similar piece of code at https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L1689 that we could remove as well.

**Comment by georgekankava** [comment]
Done! Thank you:)

**Comment by saudet** [comment]
Please squash this into one commit, and I'll merge it in! Thank you

**Comment by georgekankava** [comment]
Done!

**Pull request merged**
