### PR TITLE
long pointers

### PR DESCRIPTION
**Pull request by agibsonccc**
Adds long pointers - WIP.  Need to resolve jni adapter issues yet.

### CODE REVIEW

**Comment by agibsonccc** [comment]
Errors associated with it: https://gist.github.com/agibsonccc/e6d647717da28f344cf6

**Comment by saudet** [comment]
I was worried that because 64-bit arithmetic in Java doesn't get optimized very well that maybe `GetLongField()` would be slower than `GetIntField()` even on 64-bit architecture, but I've confirmed that this isn't the case. They both run in ~5 ns with OpenJDK 8. So, it doesn't look like we would suffer any performance degradation. The memory footprint of each Pointer almost doubles though, but it looks like that would be the only downside. And even there, it would only be significant when keeping a large amount of Pointer objects in memory that refer to small areas of memory, and I don't believe anyone currently needs to use that way.

**Comment by agibsonccc** [comment]
What if you have a "mode" for pointer memory? Or maybe have a new module/pointer factory? You could implement both over loading of ints and longs.

**Comment by saudet** [comment]
I don't think it's worth the trouble, that's the point. I have to give this a little bit more thought though, obviously. :)

**Comment by saudet** [comment]
Merged into the longptr branch: https://github.com/bytedeco/javacpp/tree/longptr

**Pull request closed without merging**
