### PR TITLE
#61 dedup all the classes for which the code needs to be generated

### PR DESCRIPTION
**Pull request by 243826**

### CODE REVIEW

**Comment by saudet** [comment]
Is this something that happens with the sample `pipeline.zip` you posted in issue #61?

**Comment by 243826** [comment]
yes. when I provide package name as argument, it detects that CPPOutputPort.class needs to be included as well _twice_. I assume once per class in the package.

**Comment by saudet** [comment]
I see, your changes seem to fix the issue alright. So, we should be using a `Set` there instead of a `List` from the start. What about changing the type of `map` to `LinkedHashMap<String, Set<Class>>` and putting `new LinkedHashSet<Class>()` into that instead of `new ArrayList<Class>()`? Plus, that should preserve the order in which the classes are currently returned.

**Comment by 243826** [comment]
I had the same thought about LinkedHashSet. It's a quick fix - I will augment the PR.

Regarding "using Set from the start", I actually started down that path but soon realized that my changes were actually percolating into a huge change set in the code which I hardly understood. I am not comfortable doing it myself.

**Comment by saudet** [comment]
Actually, no, it's not a big change. The map object is only used in that
method. It doesn't go outside!

**Comment by 243826** [comment]
You are right. I have updated the PR.

**Comment by saudet** [comment]
Looks great! Thanks a lot :)

**Pull request merged**
